Added makefile, misc changes
felix-elugbaju/Group_B_VirtualEscapeRoom pull request #25
Opened 2020-12-06 17:47 UTC by felix-elugbaju

Added makefile to build project

Changed some code formatting

2020-12-06 18:16 UTC, AlviJawad commented
Please make individual commits for each of the major changes that you make. I see some files got reuploaded only, which doesn't make sense. Please pull first and then add your changes only, do push your entire local directory.

2020-12-06 18:20 UTC, AlviJawad requested changes
This does not make any sense to be a commit

2020-12-06 18:39 UTC, felix-elugbaju commented
> If you remove the extern keyword, it causes problems when you're trying to access the same function from a different file.

Functions in header files need not be declared `extern`. Header files should be included in C source files via `#include`, for which `extern` is not necessary. Please refer to [this stack overflow link](https://stackoverflow.com/a/3367184). Header files should only contain struct definitions, function prototypes, and preprocessor defines.

2020-12-08 16:21 UTC, johnjegede reviewed
This is not the way the make file should be. this pull wont be added to the project

2020-12-12 16:46 UTC, Isaac-Wiebe requested changes
Can you close this pull request? As I have successfully implemented the Makefile John gave me into the project, that was based on theDemo 1 Makefile.

2020-12-13 15:45 UTC, closed without merging